
import imageData from "../images/images";
 
export const products = [
  {
    id : 1, 
    name: 'Cropped Stay Groovy off white',
    price: 10.9,
    count: 9,
    quantity : 1,
    details:'X | White T-shirt',
    frontSrc: imageData.image1,
    backSrc: imageData.image1_back,
  },
  {
    id : 2,
    name: 'Basic Cactus White T-shirt',
    price: 13.25,
    count: 3,
    quantity : 1,
    details:'X | Wine',
    frontSrc: imageData.image2,
    backSrc: imageData.image2_back,
  },
  {
    id : 3,
    name: 'Skater Black Sweatshirt',
    price: 25.9,
    count: 12,
    quantity : 1,
    details:'XL | Tony Hawk',
    frontSrc: imageData.image3,
    backSrc: imageData.image3_back,
  },
  {
    id : 4,
    name: 'Black Tule Oversized',
    price: 29.45,
    count: 5,
    quantity : 1,
    details:'M | Tule',
    frontSrc: imageData.image4,
    backSrc: imageData.image4_back,
  },
  {
    id : 5,
    name: 'Black Batman T-shirt',
    price: 10.9,
    count: 9,
    quantity : 1,
    details:'S | Really Cool T-shirt',
    frontSrc: imageData.image5,
    backSrc: imageData.image5_back,
  },
  {
    id : 6,
    name: 'Blue T-Shirt',
    price: 9.0,
    count: 3,
    quantity : 1,
    details:'X | Mark Zuck have 365 of this one',
    frontSrc: imageData.image6,
    backSrc: imageData.image6_back,
  },
  {
    id : 7,
    name: 'Loose Black T-shirt',
    price: 14.0,
    count: 5,
    quantity : 1,
    details:'X | Black T-Shirt',
    frontSrc: imageData.image7,
    backSrc: imageData.image7_back,
  },
  {
    id : 8,
    name: 'Ringer Hall Pass',
    price: 10.9,
    count: 9,
    quantity : 1,
    details:'X | White T-shirt',
    frontSrc: imageData.image8,
    backSrc: imageData.image8_back,
  },
  {
    id : 9,
    name: 'Grey T-shirt',
    price: 14.9,
    count: 7,
    quantity : 1,
    details:'X | You will like this one',
    frontSrc: imageData.image9,
    backSrc: imageData.image9_back,
  },
  {
    id : 10,
    name: 'Black T-shirt with white stripes',
    price: 14.9,
    count: 7,
    quantity : 1,
    details:'X | Adidas originals',
    frontSrc: imageData.image10,
    backSrc: imageData.image10_back,
  },
  {
    id : 11,
    name: 'Turtles Ninja T-shirt',
    price: 10.9,
    count: 9,
    quantity : 1,
    details:'X | Cowabunga!',
    frontSrc: imageData.image11,
    backSrc: imageData.image11_back,
  },
  {
    id : 12,
    name: 'Slim black T-shirt',
    price: 49.9,
    count: 1,
    quantity : 1,
    details:'XL | When you wish well',
    frontSrc: imageData.image12,
    backSrc: imageData.image12_back,
  },
  {
    id : 13,
    name: 'Blue Sweatshirt',
    price: 22.5,
    count: 4,
    quantity : 1,
    details:'S | Very comfy',
    frontSrc: imageData.image13,
    backSrc: imageData.image13_back,
  },
  {
    id : 14,
    name: 'White T-shirt Gucci',
    price: 18.7,
    count: 4,
    quantity : 1,
    details:'S | Very comfy',
    frontSrc: imageData.image14,
    backSrc: imageData.image14_back,
  },
  {
    id : 15,
    name: 'Tropical Wine T-shirt',
    price: 134.9,
    count: 5,
    quantity : 1,
    details:'L | Red T-shirt',
    frontSrc: imageData.image15,
    backSrc: imageData.image15_back,
  },
  {
    id : 16,
    name: 'Marine Blue T-shirt',
    price: 49.9,
    count: 9,
    quantity : 1,
    details:'L | Grey T-shirt',
    frontSrc: imageData.image16,
    backSrc: imageData.image16_back,
  },
];